"""Export the real per-agent budget envelope from MVP_REGISTRY to JSON.

WHY THIS EXISTS
---------------
The agent-spec and agent-network generators are Node/JS; the truth
(`MVP_REGISTRY`, src/skylize/contracts/registry.py) is Python. There is no
Python->JS bridge at generation time, and there cannot be one here: the spec
gate in scripts/check_agent_network_data.py runs `gen_agent_specs.js` inside a
sandbox that copies ONLY `docs/` and `scripts/`
(check_agent_network_data.py:159-169). `src/` does not exist there, so anything
that reads src/skylize/contracts/ AT GENERATION TIME breaks that gate.

So the contract values are exported AHEAD of generation, into a committed JSON
file under `scripts/` (which the sandbox does copy), and both generators read
that file. The JSON is a GENERATED, COMMITTED artifact -- the same shape of
thing as the manifest CSV and the two roster files.

DRIFT: a contract change without a re-export would leave the JSON stale. That is
the identical failure mode the roster gate already guards for the UI data files,
and it is guarded the same way: tests/test_contract_budget_export.py re-runs this
exporter and fails if the committed JSON differs, and additionally fails if any
generated spec disagrees with the live registry.

Run from the repository root:  python scripts/export_contract_budgets.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "contract_budgets.json"


def build() -> dict[str, object]:
    """Return the JSON payload: {agent_id: {max_token_budget, max_execution_time_seconds}}."""
    sys.path.insert(0, str(ROOT / "src"))
    from skylize.contracts.registry import MVP_REGISTRY

    budgets = {
        contract.agent_id: {
            "max_token_budget": contract.max_token_budget,
            "max_execution_time_seconds": contract.max_execution_time_seconds,
        }
        for contract in sorted(MVP_REGISTRY.all(), key=lambda c: c.agent_id)
    }
    return {
        "_comment": (
            "GENERATED by scripts/export_contract_budgets.py from MVP_REGISTRY "
            "(src/skylize/contracts/registry.py). DO NOT EDIT BY HAND. Re-run the "
            "exporter after any AgentContract budget change; "
            "tests/test_contract_budget_export.py fails if this file is stale."
        ),
        "budgets": budgets,
    }


def render() -> str:
    return json.dumps(build(), indent=2, sort_keys=False) + "\n"


def main() -> int:
    OUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(build()['budgets'])} contracts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
